export { default as LOGO } from "./logo.png";
export { default as MAINHERO } from "./Banner/Hero-Banner.png";
export { default as MAINHEROONM } from "./Banner/Hero-Banner-mobile.png";
export { default as PRODUCT1 } from "./Frame 7.png";
export { default as MAINSUBHERO1 } from "./Banner/MainSubHero1.png";
export { default as MAINSUBHERO2 } from "./Banner/MainSubHero2.png";
export { default as CATEGORYHERO } from "./Banner/CategoryHero.png";
export { default as CATEGORYHEROONMOBILE } from "./Banner/CategoryHeroOnMobile.png";
export { default as MAINSUBHERO1ONMOBILE } from "./Banner/MainSubHero1OnMobile.png";
export { default as PARTNER1 } from "./Partner/Partner1.png";
export { default as PARTNER2 } from "./Partner/Partner2.png";
export { default as PARTNER3 } from "./Partner/Partner3.png";
export { default as PARTNER4 } from "./Partner/Partner4.png";
export { default as PARTNER5 } from "./Partner/Partner5.png";
export { default as PARTNER6 } from "./Partner/Partner6.png";
export { default as PARTNER7 } from "./Partner/Partner7.png";
export { default as BLOGIMAGE } from "./image 3.png";
export { default as TEST1 } from "./test/andre-tan-70EmnzDQxpY-unsplash.jpg";
export { default as TEST2 } from "./test/andre-tan-ZQ_0jk66-1E-unsplash.jpg";
export { default as TEST3 } from "./test/charlotte-rush-odJtBMxGEfk-unsplash.jpg";
export { default as TEST4 } from "./test/gabriel-yuji-aAdlMg737Ms-unsplash.jpg";
export { default as TEST5 } from "./test/image 2.png";
export { default as TEST6 } from "./test/maxim-izbash-NEZLJ54ezP4-unsplash.jpg";
export { default as TEST7 } from "./test/petr-magera-W-suV77e-U8-unsplash.jpg";
export { default as TEST8 } from "./test/petr-magera-YpDe1bKAo4A-unsplash.jpg";
export { default as TEST9 } from "./test/petr-magera-v1pzr380qbo-unsplash.jpg";
export { default as PLACEHOLDERIMAGE } from "./PlaceholderImage/No-Image-Available.jpg";
export { default as CUSTOMERP1 } from "./Customer/image 22.png";
export { default as CUSTOMERP2 } from "./Customer/image 22-1.png";
export { default as CUSTOMERP3 } from "./Customer/image 22-2.png";
export { default as CUSTOMERP4 } from "./Customer/image 22-3.png";
export { default as CUSTOMERP5 } from "./Customer/image 22-4.png";
export { default as CUSTOMERP6 } from "./Customer/image 22-5.png";
